# ----------------------------------------
# COMMON
# ----------------------------------------
spring:
  application:
    name: simple-library

---

# ----------------------------------------
# DEV
# ----------------------------------------
spring:
  profiles: default, dev

---

# ----------------------------------------
# PROD
# ----------------------------------------
spring:
  profiles: prod